#!/usr/bin/env perl

use strict;
use warnings;

use feature qw(say);

use Data::Dumper;
use JSON qw(decode_json);
use LWP::UserAgent;  

my $url = $ARGV[0];

die "you must provide a url\n" if !$url;

my $ua = LWP::UserAgent->new(ssl_opts => { verify_hostname => 1 });  
my $response = $ua->get($url);

if ($response->is_success){  
    say "URL: $url";
    say "RES: " . Dumper(decode_json($response->content));
}
elsif ($response->is_error){  
    say "Error:$url";  
    say $response->error_as_HTML;  
}  
